name: Release and deploy Todo

on:
  push:
    branches:
    - "v[0-9].[0-9]"

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
  