name: Release and deploy Todo

on:
  push:
    branches:
    - "v[0-9]+.[0-9]+"

jobs:
  release-and-deploy:

    if: "!contains(github.event.commits[0].message, '#NORUN')"
    runs-on: ubuntu-latest
    steps:
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - name: Send JSON data to SLACK
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              { 
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdown",
                    "text": "*Name:*/n${{ secrets.Name }}"
                  },
                  {
                    "type": "mrkdown",
                    "text": "*Metriculation:*/n${{ secrets.METRICULATION_NUMBER }}"
                  }
                ]
              },
              { 
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdown",
                    "text": "*Email:*/n<${{ secrets.EMAIL }}>"
                  },
                  {
                    "type": "mrkdown",
                    "text": "*Repository:*/n<${{ secrets.REPOSITORY }}>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdown",
                    "text": "*Deployment:*/n<${{ secrets.DEPLOYMENT }}>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdown",
                    "text": "<${{ secrets.DEPLOYMENT }}|Open Application>"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL1 }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  